### PR TITLE
[EPIC-1335] Refactor and convert the Public GitHub Examples of Classic Components

### PR DESCRIPTION
**Pull request by Superkachenya**

### CODE REVIEW

**Comment by sebastato** [comment]
Bugs Standard Demo: 

- The license must be removed again, this is public source code
- "[Storyboard] Unknown class BarCodeTypesListTableViewCell in Interface Builder file" message when opening the barcode type selection
- Document scanner colors (navigation bar and status bar) are weird and wrong in Dark Mode
- Text Line Recognizer Demo, Machine Readable Zones Demo, EU License Plate Scanner Demo, Blurriness Estimator Demo have wrong navigation bar color in Dark Mode
- TIFF Demo has entirely different colors

**Comment by sebastato** [comment]
Bugs RTU-UI Demo:
- Lots of Objective-C code not yet converted, filter the project navigator by ".m"

**Comment by sebastato** [comment]
Bugs SwiftUI Demo:
- Crashes on start, ScanbotSDK.framework must be embedded and signed into the app
- Document Scanner has weird layout with big black bottom bar

**Comment by Superkachenya** [comment]
> * Document Scanner has weird layout with big black bottom bar

This is the grid view for snapped images

**Review by sebastato — APPROVED** [review]

**Comment by hudson-pierce** [comment]
run tests

**Review by eddyfrank — APPROVED** [review]

**Comment by eddyfrank** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Pull request merged**
